export type StoredConnector = {
  local: [number, number, number];
  axis: [number, number, number];
  kind: "round" | "axle";
  role: "socket" | "shaft";
  diameter: number;
  length?: number;
};

// Mapas revisados exportados desde el editor de Sim Studio. Las medidas están
// expresadas en unidades Studio: un tramo Technic (1L) equivale a 1 unidad.
export const preloadedConnectionMaps: Record<string, StoredConnector[]> = {
  "11214": [
    {
      local: [-1, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 2,
    },
    {
      local: [1, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
  ],
  "15100": [
    {
      local: [0.025, 0, 0],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [1, 0, 0],
      axis: [-1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
  ],
  "18651": [
    {
      local: [-1, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0.5, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "shaft",
      diameter: 0.8,
      length: 2,
    },
  ],
  "2825": [
    {
      local: [0, -0.25, -1],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, -0.25, -2],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, -0.25, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, -0.25, -3],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
  ],
  "32013": [
    {
      local: [0, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0, 0, 1],
      axis: [0, 0, 1],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
      length: 1,
    },
  ],
  "32054": [
    {
      local: [1, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [-1, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
  ],
  "32056": [
    {
      local: [1, 0, 0],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, 0, -1],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
      length: 0.5,
    },
    {
      local: [2, 0, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
      length: 0.5,
    },
    {
      local: [0, 0, -2],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
      length: 0.5,
    },
  ],
  "32140": [
    ...[-1, -2, -3].map((z) => ({
      local: [0, 0, z] as [number, number, number],
      axis: [0, 1, 0] as [number, number, number],
      kind: "round" as const,
      role: "socket" as const,
      diameter: 0.8,
      length: 1,
    })),
    {
      local: [1, 0, -3],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
      length: 1,
    },
  ],
  "32271": [
    ...[-1, -2, -3, -4, -5, -6].map((z) => ({
      local: [0, 0, z] as [number, number, number],
      axis: [0, 1, 0] as [number, number, number],
      kind: "round" as const,
      role: "socket" as const,
      diameter: 0.8,
      length: 1,
    })),
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
      length: 1,
    },
    {
      local: [0.8, 0, -6.6],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [1.6, 0, -7.2],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
      length: 1,
    },
  ],
  "32449": [
    {
      local: [0, 0, 0.5],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, 0, -0.5],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, 0, -1.5],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, 0, 1.5],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
  ],
  "3673": [
    {
      local: [-0.5, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0.5, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
  ],
  "41677": [
    {
      local: [0, 0, -1],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
  ],
  "60483": [
    {
      local: [0, 0, -1],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
  ],
  "6558": [
    {
      local: [-1, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [1, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
  ],
  "6632": [
    {
      local: [0, 0, -1],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
    {
      local: [0, 0, -2],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
  ],
  "87082": [
    {
      local: [-1, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [1, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "shaft",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
  ],
  "10197": [
    {
      local: [0, 1, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "shaft",
      diameter: 0.6,
      length: 1,
    },
    {
      local: [0, 0, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0, 0, 1],
      axis: [0, 0, 1],
      kind: "axle",
      role: "shaft",
      diameter: 0.6,
      length: 1,
    },
  ],
  "22961": [
    {
      local: [1, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "shaft",
      diameter: 0.6,
      length: 1,
    },
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
  ],
  "27940": [
    {
      local: [1, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "shaft",
      diameter: 0.6,
      length: 1,
    },
    {
      local: [-1, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "shaft",
      diameter: 0.6,
      length: 1,
    },
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
  ],
  "32184": [
    {
      local: [0, 1, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
    {
      local: [0, -1, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
    {
      local: [0, 0, 0],
      axis: [0, 0, 1],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
  ],
  "32269": [
    {
      local: [0, 0, 0],
      axis: [0, 1, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
      length: 1,
    },
  ],
  "32270": [
    {
      local: [0, 0, 0],
      axis: [0, 0, 1],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
  ],
  "32291": [
    {
      local: [0, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
    {
      local: [0.5, -1, 0],
      axis: [0, 0, 1],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
    {
      local: [-0.5, -1, 0],
      axis: [0, 0, 1],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
  ],
  "41678": [
    {
      local: [-0.75, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
    {
      local: [0.75, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
    {
      local: [-0.5, 0, 1],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
    {
      local: [0.5, 0, 1],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
  ],
  "42003": [
    {
      local: [0, 1, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
    {
      local: [0, 0, 0],
      axis: [0, 0, 1],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
    {
      local: [0, -1, 0],
      axis: [0, 0, 1],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
  ],
  "48989": [
    {
      local: [0, 1, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0, -1, 0],
      axis: [1, 0, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 1,
    },
    {
      local: [0, 0, 0],
      axis: [0, 0, 1],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
    ...[1, -1].flatMap((y) =>
      [1, -1].map((z) => ({
        local: [0, y, z] as [number, number, number],
        axis: [0, 0, Math.sign(z)] as [number, number, number],
        kind: "round" as const,
        role: "shaft" as const,
        diameter: 0.8,
        length: 1,
      })),
    ),
  ],
  "6536": [
    {
      local: [0, 0, 0],
      axis: [1, 0, 0],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
    {
      local: [0, -1, 0],
      axis: [0, 0, 1],
      kind: "round",
      role: "socket",
      diameter: 0.8,
      length: 0.5,
    },
  ],
  "6538c": [
    {
      local: [0, 0, 0.51],
      axis: [0, 0, 1],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
    {
      local: [0, 0, -0.49],
      axis: [0, 0, 1],
      kind: "axle",
      role: "socket",
      diameter: 0.6,
    },
  ],
  "87408": [
    {
      local: [0, 0.5, 0],
      axis: [0, 1, 0],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
    ...[
      [2.5, -1.25],
      [1.5, -1.25],
      [2.5, 1.25],
      [1.5, 1.25],
    ].map(([y, z]) => ({
      local: [0, y, z] as [number, number, number],
      axis: [0, 0, 1] as [number, number, number],
      kind: "round" as const,
      role: "socket" as const,
      diameter: 0.8,
    })),
    ...[-1, 1].map((z) => ({
      local: [0, 0.5, z] as [number, number, number],
      axis: [0, 1, 0] as [number, number, number],
      kind: "axle" as const,
      role: "socket" as const,
      diameter: 0.6,
      length: 1,
    })),
  ],
  "92907": [
    ...[-0.75, 0.75].flatMap((x) =>
      [0, 1].map((z) => ({
        local: [x, -1, z] as [number, number, number],
        axis: [1, 0, 0] as [number, number, number],
        kind: "axle" as const,
        role: "socket" as const,
        diameter: 0.6,
      })),
    ),
    {
      local: [0, 0, 0],
      axis: [0, 0, 1],
      kind: "round",
      role: "socket",
      diameter: 0.8,
    },
  ],
};
